# Generated by Django 5 on project creation.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('service_interest', models.CharField(choices=[('ai-strategy', 'AI Strategy'), ('ai-chatbot', 'AI Chatbot / Assistant'), ('rag-knowledge', 'RAG / Knowledge Assistant'), ('llm-fine-tuning', 'LLM Fine-tuning'), ('speech-ai', 'Speech AI'), ('website-development', 'Website Development'), ('web-application-development', 'Web Application Development'), ('automation-backend-systems', 'Automation / Backend Systems'), ('data-pipelines-scraping', 'Data Pipelines / Scraping'), ('product-mvp-build', 'Product / MVP Build'), ('research-collaboration', 'Research Collaboration'), ('other', 'Other')], max_length=50)),
                ('budget', models.CharField(blank=True, choices=[('under-3000', 'Under $3,000'), ('3000-10000', '$3,000 – $10,000'), ('10000-25000', '$10,000 – $25,000'), ('25000-plus', '$25,000+'), ('discuss', "Let's discuss")], max_length=30)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('inquiry_type', models.CharField(choices=[('project', 'Project Inquiry'), ('partnership', 'Partnership'), ('research', 'Research Collaboration'), ('other', 'Other')], default='project', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
